version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile

    image: my-user-service:latest

    container_name: user-service-container

    ports:
      - "8081:8081"

  task-service:
    build:
      context: ./task-manager
      dockerfile: Dockerfile

    image: my-task-service:latest
    container_name: task-service-container
    ports:
      - "8082:8082"
